# Serve DHCP/DNS only on the LAN NIC
interface=enp1s0
bind-interfaces

# Don't read /etc/resolv.conf (systemd-resolved), use our own upstreams
no-resolv
server=8.8.8.8
server=192.168.1.1
# (Optional) another privacy resolver:
# server=9.9.9.9

# Hand out addresses and the router/DNS info
dhcp-range=192.168.2.10,192.168.2.250,255.255.255.0,12h
dhcp-option=3,192.168.2.1         # default gateway
dhcp-option=6,192.168.2.1         # DNS = this box

# Nice extras
domain=lan
expand-hosts
# Static reservation example:
# dhcp-host=AA:BB:CC:DD:EE:FF,10.10.10.10,set:mybox,12h



#Static DNS resolvers
address=/workbook.justanotherdomain.us/192.168.2.201
address=/mainlaptop.justanotherdomain.us/192.168.2.202
address=/laptopserver.justanotherdomain.us/192.168.2.203
address=/laptoprouter.justanotherdomain.us/192.168.2.1
address=/atlas.justanotherdomain.us/192.168.2.202
address=/gambit.justanotherdomain.us/192.168.2.202

#DHCP reservations
#This is a reservation for my phone. It has custom rules in squid for specific anti-distractions 
dhcp-host=0A:E4:AA:44:CE:32,192.168.2.200

dhcp-host=00:be:43:6c:ea:f5,192.168.2.93,worklaptop.justanotherdomain.us
dhcp-host=20:79:18:34:0a:71,192.168.2.201,workbook.justanotherdomain.us
dhcp-host=8c:47:be:48:d7:46,192.168.2.202,mainlaptop.justanotherdomain.us
dhcp-host=8c:47:be:48:d8:44,192.168.2.203,laptopserver.justanotherdomain.us

